### ISSUE TITLE
Maximum data rate? 

### ISSUE THREAD

**Issue by RandoSY** [bittysoftware/bitty_data_logger_device_code#1]
Hi,

Cool stuff!

Just wondering what the max data rate is to get data from the accelerometer?

Thanks!

**Comment by panggihsieh** [comment]
Hi happened events:
Error: device is not running the required Bluetooth services
how to solve ? (iphone 10 vs microbit Interface Version: 0241)

**Comment by bittysoftware** [comment]
Hi, sorry for the delay responding! Must have missed a notification. Data rate might not be the best way to assess this as the limit is not so much one relating to Bluetooth, which can provide 1 mbps at the physical layer which on micro:bit, which runs an old version of Bluetooth LE (v4.0) amounts to around 250 kbps, depending on exactly what you're doing. The limit is the rate at which the accelerometer is polled by the micro:bit system software (known as the DAL). I believe the highest rate at which an accelerometer reading can be obtained and transmitted (consisting of x, y and z parts) is once every 20ms.
